DROP TABLE IF EXISTS PRICES;
CREATE TABLE  PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    START_DATE_HOUR TIME NOT NULL,
    END_DATE DATE NOT NULL,
    END_DATE_HOUR TIME NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE NUMERIC(12,2) NOT NULL,
    CURR VARCHAR NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL
);


DROP TABLE IF EXISTS BRANDS;
CREATE TABLE  BRANDS (
    BRAND_ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_NAME VARCHAR NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL
);



--// add foreign key  to prices
ALTER TABLE PRICES ADD FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID);

--// preloaded data information
-- // BRANDS TABLE
INSERT INTO BRANDS (BRAND_ID,BRAND_NAME,TRANSACTION_DATE)
values (1,'ZARA',NOW());

--//PRICES TABLE
INSERT INTO PRICES
(BRAND_ID,START_DATE,START_DATE_HOUR,END_DATE,END_DATE_HOUR,PRICE_LIST,PRODUCT_ID,PRIORITY,PRICE,CURR,TRANSACTION_DATE) values
(1,'2020-06-14','00.00.00','2020-12-31','23.59.59',1,35455,0,35.50,'EUR',NOW());

INSERT INTO PRICES
(BRAND_ID,START_DATE,START_DATE_HOUR,END_DATE,END_DATE_HOUR,PRICE_LIST,PRODUCT_ID,PRIORITY,PRICE,CURR,TRANSACTION_DATE) values
(1,'2020-06-14','15.00.00','2020-06-14','18.30.00',2,35455,1,25.45,'EUR',NOW());

INSERT INTO PRICES
(BRAND_ID,START_DATE,START_DATE_HOUR,END_DATE,END_DATE_HOUR,PRICE_LIST,PRODUCT_ID,PRIORITY,PRICE,CURR,TRANSACTION_DATE) values
(1,'2020-06-15','00.00.00','2020-06-15','11.00.00',3,35455,1,30.50,'EUR',NOW());

INSERT INTO PRICES
(BRAND_ID,START_DATE,START_DATE_HOUR,END_DATE,END_DATE_HOUR,PRICE_LIST,PRODUCT_ID,PRIORITY,PRICE,CURR,TRANSACTION_DATE) values
(1,'2020-06-15','16.00.00','2020-12-31','23.59.59',4,35455,1,38.95,'EUR',NOW());














